import { Footer, Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-Jakarta bg-[url(/images/cream-marfil-tiles-2.png)]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
